spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/farmer2u
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: public

server:
  port: 8080
